UI_LANGUAGES = {
    'zh': {
        'main_msg': "机器人由<a href=\"https://t.me/gsyxyc\">宫水</a>打造\n\n-内置反广告\n-自定义欢迎语\n-定时群发消息\n\n请选择功能：",
        'panel_title': "群管面板：",
        'btn_welcome': "欢迎语设置",
        'btn_triggers': "广告触发词",
        'btn_tasks': "定时群发",
        'btn_admins': "管理员设置",
        'back_home': "返回主菜单",
        'back_level': "返回上一级",
        'welcome_msg': "请发送您想设置为欢迎语的内容（支持纯文字、单张图片、图文并发）：",
        'triggers_msg': "当前已设置的触发词：\n{}",
        'trigger_add': "新增触发词",
        'trigger_del': "删除触发词",
        'wait_add_trigger': "请发送您想新增的触发词：",
        'wait_del_trigger': "请发送您想删除的触发词：",
        'tasks_msg': "已设置的定时任务：\n{}",
        'task_add': "新增定时任务",
        'wait_task_hour': "请回复要发送的小时（0-23，如 8）：",
        'wait_task_msg': "请回复这个时间点要发送的内容：",
        'admins_msg': "当前群组管理员 ID：\n{}",
        'admin_add': "新增管理员",
        'admin_del': "删除管理员",
        'wait_add_admin': "请发送要添加的管理员的数字ID：",
        'wait_del_admin': "请发送要删除的管理员的数字ID：",
        'no_permission': "你没有权限操作此机器人。",
        'trigger_empty': "目前没有触发词。",
        'task_empty': "目前没有定时任务。",
        'admin_empty': "目前没有设置管理员，群主默认拥有权限。",
        'channel_msg': "请先加入频道后再使用机器人功能。",
        'dev_title': "开发者工具",
        'captcha_title': "验证码设置",
        'lang_title': "语言设置",
        'setting_title': "设置",
        'gsai_welcome': "欢迎使用 AI 对话功能！请输入你的问题。",
        'gsai_thinking': "正在思考中... ⏳",
        'correct_msg': "✅ 回答正确！",
        'incorrect_msg': "❌ 回答错误，请重试。",
        'lang_sel_success': "✅ 已切换到中文",
    },
    'en': {
        'main_msg': "Bot created by <a href=\"https://t.me/gsyxyc\">Gong Shui</a>\n\n- Built-in anti-spam\n- Custom welcome message\n- Scheduled group messages\n\nPlease select a feature:",
        'panel_title': "Group Management Panel:",
        'btn_welcome': "Welcome Message",
        'btn_triggers': "Spam Triggers",
        'btn_tasks': "Scheduled Messages",
        'btn_admins': "Admin Settings",
        'back_home': "Back to Home",
        'back_level': "Back",
        'welcome_msg': "Send the content you want to set as a welcome message (text, image, or both):",
        'triggers_msg': "Current triggers:\n{}",
        'trigger_add': "Add Trigger",
        'trigger_del': "Delete Trigger",
        'wait_add_trigger': "Send the trigger word you want to add:",
        'wait_del_trigger': "Send the trigger word you want to delete:",
        'tasks_msg': "Scheduled tasks:\n{}",
        'task_add': "Add Task",
        'wait_task_hour': "Reply with the hour to send (0-23, e.g., 8):",
        'wait_task_msg': "Reply with the message to send at this time:",
        'admins_msg': "Current group admins:\n{}",
        'admin_add': "Add Admin",
        'admin_del': "Remove Admin",
        'wait_add_admin': "Send the numeric ID of the admin to add:",
        'wait_del_admin': "Send the numeric ID of the admin to remove:",
        'no_permission': "You don't have permission to use this bot.",
        'trigger_empty': "No triggers set yet.",
        'task_empty': "No scheduled tasks yet.",
        'admin_empty': "No admins set. Group owner has default permission.",
        'channel_msg': "Please join the channel first before using bot features.",
        'dev_title': "Developer Tools",
        'captcha_title': "Captcha Settings",
        'lang_title': "Language Settings",
        'setting_title': "Settings",
        'gsai_welcome': "Welcome to AI Chat! Please ask your question.",
        'gsai_thinking': "Thinking... ⏳",
        'correct_msg': "✅ Correct!",
        'incorrect_msg': "❌ Incorrect. Please try again.",
        'lang_sel_success_en': "✅ Switched to English",
    }
}
